---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  namespace: postgres-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: pocrke.azurecr.io/pgdata:v2
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: "t24db"
        - name: POSTGRES_USER
          value: "t24"
        - name: POSTGRES_PASSWORD
          value: "t24"
      imagePullSecrets:
      - name: acr-secret

---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: postgres-test
spec:
  ports:
  - port: 5432
  selector:
    app: postgres
  type: ClusterIP
