apiVersion: v1
kind: ConfigMap
metadata:
  name: "transact-config"
data:
  {{- if .Values.keycloak.enabled }}
  keycloakurl: {{ .Values.keycloak.keycloakurl | default "http://localhost:8080/realms/transact" | quote }}
  keycloakredirecturi: {{ .Values.keycloak.keycloakredirecturi | default "http://localhost:8080/Browser/Login" |quote }}
  keycloakclient: {{ .Values.keycloak.keycloakredirecturi | default "uxpbrowser" | quote }}
  {{- end }}
  jmsurl: {{ include "mq.connectionstring" . | quote }}
  jmsuser: {{ .Values.mq.user | default "user" | quote}}
  dburl: {{ include "database.connectionstring" . | quote }}
  dbuser: {{ .Values.database.user | default "jumpstart" | quote }}
  appuser: {{ .Values.app.user | default "SSOUSER1" | quote }}
  oltpactive: {{ .Values.tafjee.OLTP_ACTIVE | quote }}
  serviceactive: {{ .Values.tafjee.SERVICE_ACTIVE | quote }}
  envprefix: {{ .Values.config.name | quote }}
  {{- if .Values.ssl.enabled }}
  ssl_filename: {{ .Values.ssl.filename | quote }}
  {{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: "jboss-config"
data:
  MDB_POOL_MAX: {{ .Values.jboss.MDB_POOL_MAX | quote }}
  DB_POOL_MIN: {{ .Values.jboss.DB_POOL_MIN | quote }}
  DB_POOL_MAX: {{ .Values.jboss.DB_POOL_MAX | quote }}
  MAX_POOL_SIZE: {{ .Values.jboss.MAX_POOL_SIZE | quote }}