apiVersion: v1
kind: Secret
metadata:
  name: externals
type: Opaque
data:
  {{- if ne .Values.database.type "PostgreSQLawsWrapper" }}
  db_password: {{ .Values.database.password | b64enc }}
  {{- end }}
  {{- if .Values.keycloak.enabled }}
  keycloakclientsecret: {{.Values.keycloak.clientsecret | b64enc }}
  keycloakpkencoded: {{.Values.keycloak.pkencoded | b64enc}}
  {{- end }}
  app_password: {{ .Values.app.password | toString | b64enc }}
  {{- if .Values.ssl.enabled }}
  ssl_password: {{ .Values.ssl.password | b64enc }}
  {{- end }}
  jbossAdminPassword: {{ .Values.jboss.JBOSS_PWD | b64enc }}
  {{- if .Values.mq.password }}
  jms_password: {{ .Values.mq.password | b64enc }}
  {{- end }}
