apiVersion: v1
kind: Service
metadata:
  name: {{ include "transact.fullname" . }}{{ "-lb" }}
  labels:
    app.kubernetes.io/name: {{ include "transact.name" . }}
    helm.sh/chart: {{ include "transact.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    {{- if eq .Values.environment "aks" }}
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
    {{- end }}
spec:
  type: LoadBalancer
  {{- if .Values.apiIp }}
  loadBalancerIP: {{ .Values.api_ip }}
  {{- end }}
  ports:
    - name: http
      port: 80
      targetPort: api
      protocol: TCP
    {{- if .Values.ssl.enabled }}
    - name: https
      port: 8443
      targetPort: 8443
      protocol: TCP
    {{- end }}
  selector:
    {{- include "api.selectorLabels" . | nindent 4 }}