apiVersion: v1
kind: Service
metadata:
  name: postgres-service1
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - port: {{ .Values.service.port }}
  selector:
    app: {{ .Values.labels.app }}
  type: {{ .Values.service.type }}