apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - port: {{ .Values.service.port }}
  selector:
    app: {{ .Values.labels.app }}
  type: {{ .Values.service.type }}
