serviceAccount:
  name: sanitytest-serviceaccount

namespace: sanitytest-{{ .Release.Name }}

clusterRole:
  name: sanitytest-clusterrole

job:
  name: sanitytest-job-{{ .Release.Name }}
  image: pocrke.azurecr.io/sanitytest:latest
  configPath: /app/tests_config.json
  namespacesPath: /app/namespaces.json
  containerName: sanitytest-container

configMapNames:
  tests: tests-config
  namespaces: namespaces-config

imagePullSecrets:
  - acr-secret  # Make sure this secret exists in the namespace

buildId: "{{ .Release.Name }}"
