serviceAccount:
  name: sanitytest-serviceaccount

namespace: sanitytest-{{ .Release.Name }}

clusterRole:
  name: sanitytest-clusterrole

job:
  name: sanitytest-job-{{ .Release.Name }}
  image: pocrke.azurecr.io/sanitytest:latest
  configPath: /app/tests_config.json
  namespacesPath: /app/namespaces.json
  testCasePaths: /app/test_case_paths.json
  testCasesPath: /app/test_cases.json
  containerName: sanitytest-container

configMapNames:
  tests: tests-config
  namespaces: namespaces-config
  testCasePaths: test-case-paths-config
  testCases: test-cases-config

imagePullSecrets:
  - acr-secret  # Make sure this secret exists in the namespace

buildId: "{{ .Release.Name }}"
