serviceAccount:
  name: sanitytest-serviceaccount

namespace: sanitytest-{{ .Release.Name }}

clusterRole:
  name: sanitytest-clusterrole

job:
  name: sanitytest-job-{{ .Release.Name }}
  image: pocrke.azurecr.io/sanitytest:latest
  configPath: /app/tests_config.json
  namespacesPath: /app/namespaces.json
  testCasesPath: /app/test_cases.json
  testCasePathsPath: /app/test_case_paths.json
  containerName: sanitytest-container

configMapNames:
  testCases: test-cases-config
  testCasePaths: test-case-paths-config
  namespaces: namespaces-config

imagePullSecrets:
  - acr-secret

buildId: "{{ .Release.Name }}"
