{{- if .Values.createClusterRoleBinding }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Name }}-role-binding-{{ .Values.buildId }}
  labels:
    app.kubernetes.io/managed-by: "Helm"
subjects:
  - kind: ServiceAccount
    name: {{ .Values.serviceAccount.name }}
    namespace: {{ .Values.namespace }}
roleRef:
  kind: ClusterRole
  name: {{ .Release.Name }}-cluster-role-{{ .Values.buildId }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
