apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Name }}-cluster-role-{{ .Values.buildId }}  # Dynamic name for uniqueness
  labels:
    app.kubernetes.io/managed-by: "Helm"
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
rules:
- apiGroups: [""]  # "" indicates the core API group
  resources:
    - pods
    - pods/exec
    - pods/log
    - events
  verbs:
    - get
    - list
    - watch
    - create
    - exec
