apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Name }}-transact-role-{{ .Values.buildId }}
rules:
- apiGroups: [""]
  resources:
    - pods
    - pods/exec
    - pods/log
  verbs:
    - get
    - list
    - watch
    - create
    - exec
