apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.job.name }}
  namespace: {{ .Values.namespace }}
spec:
  template:
    metadata:
      labels:
        app: {{ .Values.job.name }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      containers:
      - name: my-container
        image: {{ .Values.job.image }}
        imagePullPolicy: IfNotPresent
        command: ["python", "/app/sanitytest_containerversion.py"]
        env:
        - name: CONFIG_PATH
          value: {{ .Values.job.configPath }}
        - name: NAMESPACES_PATH
          value: {{ .Values.job.namespacesPath }}
        - name: TEST_CASE_PATHS
          value: {{ .Values.job.testCasePaths }}
        - name: TEST_CASES_PATH
          value: {{ .Values.job.testCasesPath }}
        volumeMounts:
        - name: config-volume
          mountPath: {{ .Values.job.configPath }}
          subPath: tests_config.json
        - name: namespaces-volume
          mountPath: {{ .Values.job.namespacesPath }}
          subPath: namespaces.json
        - name: test-case-paths-volume
          mountPath: {{ .Values.job.testCasePaths }}
          subPath: test_case_paths.json
        - name: test-cases-volume
          mountPath: {{ .Values.job.testCasesPath }}
          subPath: test_cases.json
      volumes:
      - name: config-volume
        configMap:
          name: {{ .Values.configMapNames.tests }}
      - name: namespaces-volume
        configMap:
          name: {{ .Values.configMapNames.namespaces }}
      - name: test-case-paths-volume
        configMap:
          name: {{ .Values.configMapNames.testCasePaths }}
      - name: test-cases-volume
        configMap:
          name: {{ .Values.configMapNames.testCases }}
      restartPolicy: Never
